CC = gcc

ROOTDIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))

CFLAGS = -std=gnu17 -MMD -MP -I $(ROOTDIR)
CFLAGS += -Wall -Wextra -Wno-unused-variable -Wno-unused-parameter

SOURCES = $(wildcard *.c)
OBJECTS = $(patsubst %.c,%.o,$(SOURCES))
DEPENDS = $(patsubst %.c,%.d,$(SOURCES))

%.o: %.c Makefile
	$(CC) $(CFLAGS) -c $< -o $@
